job('First-Maven-Project-via-DSL') {
  description("First maven job generated by DSL on $(new Date()), the project is small maven project hosted on github")
  scm {
    git("https://github.com/aks2379/https-github.com-anshulc55-Jenkins_Upgradev3.git", 'master')
  }
  triggers {
    scm('* * * * *')
  }
  steps {
    maven('clean package', 'maven-samples/single-module/pom.xml')
  }
  publishers {
    //archive the generated jar file
    archiveArtifacts '**/*.jar'
  }
}
